//! YMF271 (OPX) sound chip emulator — libvgm FFI wrapper.
//!
//! ## Architecture
//! The YMF271 is Yamaha's "OPX" chip used in Taito F3 System arcade hardware.
//! - 48 FM slots arranged as 12 groups × 4 slots per group
//! - 12 PCM channels with ADPCM playback
//! - Clock: 16,934,400 Hz
//!
//! ## Implementation
//! Audio is generated by the libvgm C core (ymf271.c, BSD-3-Clause) compiled
//! via build.rs into a static library. `ymf271_ffi.c` wraps the static C
//! functions under stable extern-C names.
//!
//! ## Register write protocol (VGM 0xD1 [port, reg, data])
//! Each port write translates to two sequential calls to `ymf271_w`:
//!   1. `ymf271_w(chip, port*2,   reg)`  — sets the address register
//!   2. `ymf271_w(chip, port*2+1, data)` — triggers the register write
//!
//! ## References
//! - `src/chips/vendor/libvgm/emu/cores/ymf271.c` — MAME port, BSD-3-Clause
//! - `docs/design/YMF271_OPL4_Implementation.md`

use std::os::raw::c_void;

use super::SoundChipEmulator;

const CLOCK: u32 = 16_934_400;

#[cfg(not(target_arch = "wasm32"))]
extern "C" {
    fn ymf271_ffi_create(clock: u32) -> *mut c_void;
    fn ymf271_ffi_destroy(chip: *mut c_void);
    fn ymf271_ffi_reset(chip: *mut c_void);
    fn ymf271_ffi_write(chip: *mut c_void, offset: u8, data: u8);
    fn ymf271_ffi_update(chip: *mut c_void, samples: u32, left: *mut i32, right: *mut i32);
    fn ymf271_ffi_alloc_rom(chip: *mut c_void, rom_size: u32);
    fn ymf271_ffi_write_rom(chip: *mut c_void, offset: u32, length: u32, data: *const u8);
}

// wasm32-unknown-unknown has no libc, so the libvgm C core is not compiled (see
// build.rs). Audio playback is a native-only feature; the WASM build only uses
// the MML compiler. These stubs let the struct compile but panic if invoked.
#[cfg(target_arch = "wasm32")]
#[allow(clippy::missing_safety_doc)]
mod wasm_stubs {
    use std::os::raw::c_void;
    const MSG: &str = "YMF271 emulator is not available on wasm32";
    pub unsafe fn ymf271_ffi_create(_clock: u32) -> *mut c_void { panic!("{}", MSG) }
    pub unsafe fn ymf271_ffi_destroy(_chip: *mut c_void) {}
    pub unsafe fn ymf271_ffi_reset(_chip: *mut c_void) { panic!("{}", MSG) }
    pub unsafe fn ymf271_ffi_write(_chip: *mut c_void, _offset: u8, _data: u8) { panic!("{}", MSG) }
    pub unsafe fn ymf271_ffi_update(_chip: *mut c_void, _samples: u32, _left: *mut i32, _right: *mut i32) { panic!("{}", MSG) }
    pub unsafe fn ymf271_ffi_alloc_rom(_chip: *mut c_void, _rom_size: u32) { panic!("{}", MSG) }
    pub unsafe fn ymf271_ffi_write_rom(_chip: *mut c_void, _offset: u32, _length: u32, _data: *const u8) { panic!("{}", MSG) }
}
#[cfg(target_arch = "wasm32")]
use wasm_stubs::*;

/// YMF271 (OPX) chip emulator backed by the libvgm C core.
pub struct YMF271 {
    chip: *mut c_void,
    rom: Vec<u8>,
    rom_loaded: bool,
}

unsafe impl Send for YMF271 {}
unsafe impl Sync for YMF271 {}

impl YMF271 {
    pub fn new() -> Self {
        let chip = unsafe { ymf271_ffi_create(CLOCK) };
        assert!(!chip.is_null(), "ymf271_ffi_create returned null");
        Self { chip, rom: Vec::new(), rom_loaded: false }
    }
}

impl Drop for YMF271 {
    fn drop(&mut self) {
        unsafe { ymf271_ffi_destroy(self.chip); }
    }
}

impl SoundChipEmulator for YMF271 {
    fn name(&self) -> &'static str { "YMF271" }
    fn clock_rate(&self) -> u32 { CLOCK }

    fn reset(&mut self) {
        unsafe { ymf271_ffi_reset(self.chip); }
    }

    fn write(&mut self, addr: u8, data: u8) {
        unsafe {
            ymf271_ffi_write(self.chip, 0, addr);
            ymf271_ffi_write(self.chip, 1, data);
        }
    }

    fn write_port(&mut self, port: u8, addr: u8, data: u8) {
        unsafe {
            ymf271_ffi_write(self.chip, port * 2,     addr);
            ymf271_ffi_write(self.chip, port * 2 + 1, data);
        }
    }

    fn clock(&mut self) {}

    fn generate_samples(&mut self, buffer: &mut [f32], _sample_rate: u32) {
        if !self.rom.is_empty() && !self.rom_loaded {
            unsafe {
                ymf271_ffi_alloc_rom(self.chip, self.rom.len() as u32);
                ymf271_ffi_write_rom(
                    self.chip,
                    0,
                    self.rom.len() as u32,
                    self.rom.as_ptr(),
                );
            }
            self.rom_loaded = true;
        }

        let n = buffer.len();
        let mut left = vec![0i32; n];
        let mut right = vec![0i32; n];

        unsafe {
            ymf271_ffi_update(
                self.chip,
                n as u32,
                left.as_mut_ptr(),
                right.as_mut_ptr(),
            );
        }

        const SCALE: f32 = 1.0 / 32768.0;
        for (i, s) in buffer.iter_mut().enumerate() {
            *s = ((left[i] + right[i]) as f32) * (SCALE * 0.5);
        }
    }

    fn load_pcm_data(&mut self, _block_type: u8, data: &[u8]) {
        self.rom.extend_from_slice(data);
        self.rom_loaded = false;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::chips::SoundChipEmulator;

    #[test]
    fn test_ymf271_register_write_does_not_panic() {
        let mut chip = YMF271::new();
        // Write a register via port 2 (TL/ML/WF bank for slots)
        chip.write_port(2, 0x00, 0x3F);
    }

    #[test]
    fn test_ymf271_group_write_does_not_panic() {
        let mut chip = YMF271::new();
        chip.write_port(6, 0x00, 0xAB); // group 0 FNUM low
        chip.write_port(6, 0x10, 0x83); // group 0 FNUM high + key-on
    }

    #[test]
    fn test_ymf271_generates_nonzero_after_keyon() {
        let mut chip = YMF271::new();

        // Set up group 0 for 4-op FM (sync=0, already the default after calloc).
        //
        // Register layout: address = (reg << 4) | group_nibble
        //   group 0 → fm_tab[0]=0, lower nibble = 0x0
        //
        // TL=0 (max volume, reg 4) must be written per-bank (not a synced reg):
        chip.write_port(0, 0x40, 0x00); // bank 0, group 0, TL=0
        chip.write_port(1, 0x40, 0x00); // bank 1, group 0, TL=0
        chip.write_port(2, 0x40, 0x00); // bank 2, group 0, TL=0
        chip.write_port(3, 0x40, 0x00); // bank 3, group 0, TL=0
        // AR=31 (fastest attack, reg 5) — also per-bank:
        chip.write_port(0, 0x50, 0x1f);
        chip.write_port(1, 0x50, 0x1f);
        chip.write_port(2, 0x50, 0x1f);
        chip.write_port(3, 0x50, 0x1f);
        // Channel output enable (reg 0xd), send to ch0+ch1 — synced via bank 0:
        chip.write_port(0, 0xd0, 0xff);
        // FNUM hi (reg 0xa) — synced via bank 0: block=4, fnum_hi=0
        chip.write_port(0, 0xa0, 0x40);
        // FNUM lo (reg 9) — synced via bank 0: fnum_lo=0x80
        chip.write_port(0, 0x90, 0x80);
        // Key-on (reg 0) — synced via bank 0: fires all 4 operators in group 0
        chip.write_port(0, 0x00, 0x01);

        let mut buf = vec![0.0f32; 1024];
        chip.generate_samples(&mut buf, 44100);
        let any_nonzero = buf.iter().any(|&s| s != 0.0);
        assert!(any_nonzero, "YMF271 produced only silence after key-on");
    }

    #[test]
    fn test_ymf271_reset_does_not_panic() {
        let mut chip = YMF271::new();
        chip.write_port(0, 0x00, 0xFF);
        chip.reset();
    }
}
