/**
 * WASM Service
 * 
 * Handles initialization and interaction with the mml2vgm WASM module.
 * This service provides a clean API for compiling, validating, and playing MML.
 */

import type {
    CompileOptions,
    CompileResult,
    Token,
    ChipInfo,
    FormatInfo,
    PlayerState,
    VgmHeaderInfo,
    SoundChip,
    OutputFormat,
} from '@/types';

// ============================================================================
// WASM Module Types (from wasm-bindgen)
// ============================================================================

/** Opaque handle to a chip player (from WASM) */
export interface WasmChipPlayer {
    free(): void;
}

/** Opaque handle to a VGM player (from WASM) */
export interface WasmVgmPlayer {
    free(): void;
}

// ============================================================================
// WASM Service Class
// ============================================================================

/**
 * Service for interacting with the mml2vgm WASM module.
 * 
 * This class manages WASM initialization, compilation, validation,
 * tokenization, and audio playback.
 */
export class WasmService {
    private static instance: WasmService | null = null;
    
    // WASM module and initialization state
    private wasmModule: any = null;
    private _isInitialized: boolean = false;
    private _isInitializing: boolean = false;
    private initError: Error | undefined = undefined;
    
    // Callbacks for initialization
    private initCallbacks: Array<(success: boolean, error?: Error) => void> = [];
    
    // Chip players
    private chipPlayers: Map<string, WasmChipPlayer> = new Map();
    private nextChipPlayerId: number = 1;
    
    // VGM players
    private vgmPlayers: Map<string, WasmVgmPlayer> = new Map();
    private nextVgmPlayerId: number = 1;
    
    // Audio context for sample playback
    private audioContext: AudioContext | null = null;
    private audioWorkletNode: AudioWorkletNode | null = null;
    private sampleQueue: Float32Array[] = [];
    private isPlaying: boolean = false;
    
    /**
     * Get the singleton instance of the WASM service.
     */
    public static getInstance(): WasmService {
        if (!WasmService.instance) {
            WasmService.instance = new WasmService();
        }
        return WasmService.instance;
    }
    
    /**
     * Create a new WASM service instance.
     * Use getInstance() for singleton access.
     */
    private constructor() {}

    /**
     * Check if the WASM module is initialized.
     */
    public get isInitialized(): boolean {
        return this._isInitialized;
    }
    
    // ========================================================================
    // Initialization
    // ========================================================================
    
    /**
     * Initialize the WASM module.
     * Must be called before any other methods.
     */
    public async init(): Promise<void> {
        if (this._isInitialized) {
            return;
        }
        
        if (this._isInitializing) {
            // Wait for existing initialization
            return new Promise((resolve, reject) => {
                this.initCallbacks.push((success, error) => {
                    if (success) {
                        resolve();
                    } else {
                        reject(error || new Error('WASM initialization failed'));
                    }
                });
            });
        }
        
        this._isInitializing = true;
        
        try {
            // Import the WASM module
            // The module is generated by wasm-pack build
            const wasm = await import('mml2vgm-wasm');
            
            // wasm-pack generates a default async init() that fetches and instantiates
            // the .wasm binary. Without calling it, all WASM functions fail.
            if (typeof wasm.default === 'function') {
                await (wasm.default as () => Promise<unknown>)();
            }
            
            // Store the module
            this.wasmModule = wasm;
            
            // Initialize audio context
            this.audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
            
            // Load AudioWorklet processor
            await this.loadAudioWorklet();
            
            this._isInitialized = true;
            this._isInitializing = false;
            this.initError = undefined;
            
            // Notify callbacks
            this.initCallbacks.forEach(cb => cb(true));
            this.initCallbacks = [];
            
            console.log('[WASM Service] Initialized successfully');
            
        } catch (error) {
            this._isInitializing = false;
            this.initError = error as Error;
            
            // Notify callbacks
            this.initCallbacks.forEach(cb => cb(false, this.initError));
            this.initCallbacks = [];
            
            console.error('[WASM Service] Initialization failed:', error);
            throw error;
        }
    }
    
    /**
     * Check if WASM is initialized.
     */
    public isReady(): boolean {
        return this._isInitialized;
    }
    
    /**
     * Get the initialization error, if any.
     */
    public getInitError(): Error | null {
        return this.initError || null;
    }
    
    // ========================================================================
    // Compilation
    // ========================================================================
    
    /**
     * Compile MML source code to a binary format.
     * 
     * @param mml - The MML source code
     * @param options - Compilation options
     * @returns Promise resolving to the compiled binary data
     */
    public async compile(mml: string, options: CompileOptions): Promise<CompileResult> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;

        const readValue = <T>(obj: any, key: string, fallback: T): T => {
            const value = obj?.[key];
            if (typeof value === 'function') {
                try {
                    return value.call(obj) as T;
                } catch {
                    return fallback;
                }
            }
            return (value ?? fallback) as T;
        };
        
        // Convert options to JSON
        const optionsJson = JSON.stringify(options);
        
        // Call the WASM function - now returns JsCompileResult with metadata
        const result: any = wasm.compile_mml(mml, optionsJson);
        
        // Extract data and metadata from the result
        const rawData = readValue<any>(result, 'get_data', readValue<any>(result, 'data', new Uint8Array()));
        const data: Uint8Array = rawData instanceof Uint8Array ? rawData : new Uint8Array(rawData || []);

        const part_count: number = Number(readValue<any>(result, 'part_count', 0)) || 0;
        const command_count: number = Number(readValue<any>(result, 'command_count', 0)) || 0;
        const duration_samples: number = Number(readValue<any>(result, 'duration_samples', 0)) || 0;
        const duration_seconds: number = Number(readValue<any>(result, 'duration_seconds', 0)) || 0;

        const rawChips = readValue<any>(result, 'chips_used', []);
        let chips_used: SoundChip[] = [];
        if (Array.isArray(rawChips)) {
            chips_used = rawChips as SoundChip[];
        } else if (typeof rawChips === 'string') {
            try {
                chips_used = JSON.parse(rawChips) as SoundChip[];
            } catch {
                chips_used = [];
            }
        }
        
        return {
            data,
            errors: [],
            warnings: [],
            info: {
                part_count,
                command_count,
                duration_samples,
                duration_seconds,
                chips_used,
                format_version: '',
            },
        };
    }
    
    /**
     * Validate MML source code without generating output.
     * 
     * @param mml - The MML source code
     * @returns Promise that resolves if valid, rejects with error if invalid
     */
    public async validate(mml: string): Promise<void> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        wasm.validate_mml(mml);
    }
    
    /**
     * Tokenize MML source code for syntax highlighting.
     * 
     * @param mml - The MML source code
     * @returns Promise resolving to array of tokens
     */
    public async tokenize(mml: string): Promise<Token[]> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const tokensJson: string = wasm.tokenize(mml);
        return JSON.parse(tokensJson) as Token[];
    }
    
    // ========================================================================
    // Utilities
    // ========================================================================
    
    /**
     * Get a list of all supported sound chips.
     * 
     * @returns Promise resolving to array of chip information
     */
    public async getSupportedChips(): Promise<ChipInfo[]> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const chipsJson: string = wasm.get_supported_chips();
        return JSON.parse(chipsJson) as ChipInfo[];
    }
    
    /**
     * Get a list of all supported output formats.
     * 
     * @returns Promise resolving to array of format information
     */
    public async getSupportedFormats(): Promise<FormatInfo[]> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const formatsJson: string = wasm.get_supported_formats();
        return JSON.parse(formatsJson) as FormatInfo[];
    }
    
    /**
     * Parse a sound chip name string into a ChipInfo object.
     * 
     * @param chipName - The chip name (e.g., "YM2612", "OPN2")
     * @returns Promise resolving to ChipInfo object
     */
    public async parseSoundChip(chipName: string): Promise<ChipInfo> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const result = wasm.parse_sound_chip(chipName);
        return result as ChipInfo;
    }
    
    /**
     * Parse an output format string into a FormatInfo object.
     * 
     * @param formatName - The format name (e.g., "vgm", "xgm")
     * @returns Promise resolving to FormatInfo object
     */
    public async parseOutputFormat(formatName: string): Promise<FormatInfo> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const result = wasm.parse_output_format(formatName);
        return result as FormatInfo;
    }
    
    /**
     * Get default compile options.
     * 
     * @returns Promise resolving to default CompileOptions
     */
    public async getDefaultCompileOptions(): Promise<CompileOptions> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const optionsJson: string = wasm.default_compile_options();
        return JSON.parse(optionsJson) as CompileOptions;
    }
    
    /**
     * Get compile options for a specific format.
     * 
     * @param format - The output format
     * @returns Promise resolving to CompileOptions
     */
    public async getCompileOptionsForFormat(format: OutputFormat): Promise<CompileOptions> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const optionsJson: string = wasm.compile_options_for_format(format);
        return JSON.parse(optionsJson) as CompileOptions;
    }
    
    // ========================================================================
    // Chip Player
    // ========================================================================
    
    /**
     * Create a new chip player for real-time audio generation.
     * 
     * @param sampleRate - The audio sample rate (e.g., 44100)
     * @returns Promise resolving to chip player ID
     */
    public async createChipPlayer(sampleRate: number = 44100): Promise<string> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const player: WasmChipPlayer = wasm.create_chip_player(sampleRate);
        
        const id = `chip-player-${this.nextChipPlayerId++}`;
        this.chipPlayers.set(id, player);
        
        return id;
    }
    
    /**
     * Add a sound chip to a chip player.
     * 
     * @param playerId - The chip player ID
     * @param chip - The sound chip to add
     */
    public async addChipToPlayer(playerId: string, chip: SoundChip): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.chip_player_add_chip(player, chip);
    }
    
    /**
     * Write to a chip register.
     * 
     * @param playerId - The chip player ID
     * @param chip - The target chip
     * @param addr - Register address
     * @param data - Data to write
     */
    public async writeChipRegister(
        playerId: string,
        chip: SoundChip,
        addr: number,
        data: number
    ): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.chip_player_write_register(player, chip, addr, data);
    }
    
    /**
     * Set the linear mix gain for a chip on the chip player.
     * `gain = 1.0` is unity, `0.0` mutes (emulator still clocked).
     */
    public async setChipGain(
        playerId: string,
        chip: SoundChip,
        gain: number,
    ): Promise<void> {
        await this.ensureInitialized();

        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.chip_player_set_chip_gain(player, chip, gain);
    }

    /**
     * Generate audio samples from a chip player.
     * 
     * @param playerId - The chip player ID
     * @param numSamples - Number of stereo samples to generate
     * @returns Promise resolving to Float32Array of interleaved stereo samples
     */
    public async generateSamples(
        playerId: string,
        numSamples: number
    ): Promise<Float32Array> {
        await this.ensureInitialized();
        
        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        const samples: Float32Array = wasm.chip_player_generate_samples(player, numSamples);
        
        return samples;
    }
    
    /**
     * Reset a chip player.
     * 
     * @param playerId - The chip player ID
     */
    public async resetChipPlayer(playerId: string): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.chip_player_reset(player);
    }
    
    /**
     * Get the state of a chip player.
     * 
     * @param playerId - The chip player ID
     * @returns Promise resolving to player state
     */
    public async getChipPlayerState(playerId: string): Promise<PlayerState> {
        await this.ensureInitialized();
        
        const player = this.getChipPlayer(playerId);
        const wasm = this.wasmModule;
        const state: string = wasm.chip_player_state(player);
        return state as PlayerState;
    }
    
    /**
     * Start real-time sample generation and playback.
     * 
     * @param playerId - The chip player ID
     * @param bufferSize - Number of samples to generate per batch
     */
    public async startChipPlayback(
        playerId: string,
        bufferSize: number = 4096
    ): Promise<void> {
        await this.ensureInitialized();
        
        // Stop any existing playback
        await this.stopPlayback();
        
        this.isPlaying = true;
        
        // Start the playback loop
        this.playbackLoop(playerId, bufferSize);
    }
    
    /**
     * Stop real-time playback.
     */
    public async stopPlayback(): Promise<void> {
        this.isPlaying = false;
        this.sampleQueue = [];
        
        if (this.audioWorkletNode) {
            this.audioWorkletNode.disconnect();
            this.audioWorkletNode = null;
        }
    }
    
    /**
     * Internal playback loop for chip player.
     */
    private async playbackLoop(playerId: string, bufferSize: number): Promise<void> {
        if (!this.isPlaying) return;
        
        try {
            // Generate samples
            const samples = await this.generateSamples(playerId, bufferSize);
            this.sampleQueue.push(samples);
            
            // Schedule next batch
            setTimeout(() => this.playbackLoop(playerId, bufferSize), 0);
        } catch (error) {
            console.error('[WASM Service] Playback error:', error);
            this.isPlaying = false;
        }
    }
    
    /**
     * Destroy a chip player and free resources.
     * 
     * @param playerId - The chip player ID
     */
    public destroyChipPlayer(playerId: string): void {
        const player = this.chipPlayers.get(playerId);
        if (player) {
            player.free();
            this.chipPlayers.delete(playerId);
        }
    }
    
    // ========================================================================
    // VGM Player
    // ========================================================================
    
    /**
     * Create a new VGM player.
     * 
     * @returns Promise resolving to VGM player ID
     */
    public async createVgmPlayer(): Promise<string> {
        await this.ensureInitialized();
        
        const wasm = this.wasmModule;
        const player: WasmVgmPlayer = wasm.create_vgm_player();
        
        const id = `vgm-player-${this.nextVgmPlayerId++}`;
        this.vgmPlayers.set(id, player);
        
        return id;
    }
    
    /**
     * Load VGM data into a player.
     * 
     * @param playerId - The VGM player ID
     * @param data - The VGM binary data
     */
    public async loadVgm(playerId: string, data: Uint8Array): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getVgmPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.vgm_player_load(player, data);
    }
    
    /**
     * Play the loaded VGM.
     * 
     * @param playerId - The VGM player ID
     */
    public async playVgm(playerId: string): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getVgmPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.vgm_player_play(player);
    }
    
    /**
     * Stop VGM playback.
     * 
     * @param playerId - The VGM player ID
     */
    public async stopVgm(playerId: string): Promise<void> {
        await this.ensureInitialized();
        
        const player = this.getVgmPlayer(playerId);
        const wasm = this.wasmModule;
        wasm.vgm_player_stop(player);
    }
    
    /**
     * Get the state of a VGM player.
     * 
     * @param playerId - The VGM player ID
     * @returns Promise resolving to player state
     */
    public async getVgmPlayerState(playerId: string): Promise<PlayerState> {
        await this.ensureInitialized();
        
        const player = this.getVgmPlayer(playerId);
        const wasm = this.wasmModule;
        const state: string = wasm.vgm_player_state(player);
        return state as PlayerState;
    }
    
    /**
     * Get information about the loaded VGM.
     * 
     * @param playerId - The VGM player ID
     * @returns Promise resolving to VGM header info
     */
    public async getVgmInfo(playerId: string): Promise<VgmHeaderInfo> {
        await this.ensureInitialized();
        
        const player = this.getVgmPlayer(playerId);
        const wasm = this.wasmModule;
        const infoJson: string = wasm.vgm_player_get_info(player);
        return JSON.parse(infoJson) as VgmHeaderInfo;
    }
    
    /**
     * Destroy a VGM player and free resources.
     * 
     * @param playerId - The VGM player ID
     */
    public destroyVgmPlayer(playerId: string): void {
        const player = this.vgmPlayers.get(playerId);
        if (player) {
            player.free();
            this.vgmPlayers.delete(playerId);
        }
    }
    
    // ========================================================================
    // Cleanup
    // ========================================================================
    
    /**
     * Clean up all resources.
     */
    public cleanup(): void {
        // Destroy all chip players
        for (const [, player] of this.chipPlayers) {
            player.free();
        }
        this.chipPlayers.clear();
        
        // Destroy all VGM players
        for (const [, player] of this.vgmPlayers) {
            player.free();
        }
        this.vgmPlayers.clear();
        
        // Stop playback
        this.stopPlayback();
        
        // Close audio context
        if (this.audioContext) {
            this.audioContext.close();
            this.audioContext = null;
        }
        
        this._isInitialized = false;
        this.wasmModule = null;
    }
    
    // ========================================================================
    // AudioWorklet Setup
    // ========================================================================
    
    /**
     * Load the AudioWorklet processor.
     */
    private async loadAudioWorklet(): Promise<void> {
        if (!this.audioContext) {
            throw new Error('AudioContext not initialized');
        }
        
        try {
            // Check if AudioWorklet is supported
            if (!window.AudioWorklet) {
                console.warn('[WASM Service] AudioWorklet not supported, using fallback');
                return;
            }
            
            // Load the processor script
            // In production, this would be a separate file
            const processorCode = `
                class MMLAudioProcessor extends AudioWorkletProcessor {
                    constructor() {
                        super();
                        this.sampleBuffer = new Float32Array(0);
                        this.bufferIndex = 0;
                        
                        this.port.onmessage = (e) => {
                            if (e.data.type === 'samples') {
                                this.sampleBuffer = new Float32Array(e.data.samples);
                                this.bufferIndex = 0;
                            }
                        };
                    }
                    
                    process(inputs, outputs, parameters) {
                        const output = outputs[0];
                        const samplesNeeded = output[0].length;
                        
                        for (let i = 0; i < samplesNeeded; i++) {
                            if (this.bufferIndex >= this.sampleBuffer.length) {
                                // Request more samples
                                this.port.postMessage({ type: 'needSamples', count: samplesNeeded });
                                output[0][i] = 0;
                                output[1][i] = 0;
                            } else {
                                output[0][i] = this.sampleBuffer[this.bufferIndex];
                                output[1][i] = this.sampleBuffer[this.bufferIndex + 1];
                                this.bufferIndex += 2;
                            }
                        }
                        
                        return true;
                    }
                }
                
                registerProcessor('mml-audio-processor', MMLAudioProcessor);
            `;
            
            // Create a blob URL for the processor
            const blob = new Blob([processorCode], { type: 'application/javascript' });
            const url = URL.createObjectURL(blob);
            
            // Register the processor
            await this.audioContext.audioWorklet.addModule(url);
            
            // Create the AudioWorklet node
            this.audioWorkletNode = new AudioWorkletNode(
                this.audioContext,
                'mml-audio-processor'
            );
            
            // Connect to destination
            this.audioWorkletNode.connect(this.audioContext.destination);
            
            // Handle messages from the processor
            this.audioWorkletNode.port.onmessage = (e) => {
                if (e.data.type === 'needSamples') {
                    // Generate more samples when requested
                    console.log('[AudioWorklet] Need more samples:', e.data.count);
                }
            };
            
            console.log('[WASM Service] AudioWorklet loaded successfully');
            
        } catch (error) {
            console.warn('[WASM Service] Failed to load AudioWorklet:', error);
            // Fall back to ScriptProcessorNode (deprecated but more widely supported)
            this.setupScriptProcessorFallback();
        }
    }
    
    /**
     * Fallback for browsers without AudioWorklet support.
     */
    private setupScriptProcessorFallback(): void {
        if (!this.audioContext) return;
        
        console.warn('[WASM Service] Using ScriptProcessorNode fallback (deprecated)');
        
        // Create a script processor with a large buffer
        const bufferSize = 4096;
        const scriptProcessor = this.audioContext.createScriptProcessor(
            bufferSize,
            0,
            2
        );
        
        scriptProcessor.onaudioprocess = (e) => {
            const output = e.outputBuffer;
            const left = output.getChannelData(0);
            const right = output.getChannelData(1);
            
            // Fill with samples from queue or zeros
            if (this.sampleQueue.length > 0) {
                const samples = this.sampleQueue.shift()!;
                const samplesToCopy = Math.min(samples.length, left.length);
                
                for (let i = 0; i < samplesToCopy; i += 2) {
                    if (i + 1 < samples.length) {
                        left[i] = samples[i];
                        right[i] = samples[i + 1];
                    }
                }
                
                // Fill remainder with zeros
                for (let i = samplesToCopy; i < left.length; i++) {
                    left[i] = 0;
                    right[i] = 0;
                }
            } else {
                // Fill with zeros
                left.fill(0);
                right.fill(0);
            }
        };
        
        scriptProcessor.connect(this.audioContext.destination);
        this.audioWorkletNode = scriptProcessor as unknown as AudioWorkletNode;
    }
    
    // ========================================================================
    // Helper Methods
    // ========================================================================
    
    /**
     * Ensure WASM is initialized, throwing an error if not.
     */
    private async ensureInitialized(): Promise<void> {
        if (this._isInitialized) {
            return;
        }
        
        if (this._isInitializing) {
            // Wait for initialization to complete
            await new Promise((resolve, reject) => {
                this.initCallbacks.push((success, error) => {
                    if (success) {
                        resolve(void 0);
                    } else {
                        reject(error || new Error('WASM initialization failed'));
                    }
                });
            });
            return;
        }
        
        // Auto-initialize
        await this.init();
    }
    
    /**
     * Get a chip player by ID, throwing if not found.
     */
    private getChipPlayer(playerId: string): WasmChipPlayer {
        const player = this.chipPlayers.get(playerId);
        if (!player) {
            throw new Error(`Chip player not found: ${playerId}`);
        }
        return player;
    }
    
    /**
     * Get a VGM player by ID, throwing if not found.
     */
    private getVgmPlayer(playerId: string): WasmVgmPlayer {
        const player = this.vgmPlayers.get(playerId);
        if (!player) {
            throw new Error(`VGM player not found: ${playerId}`);
        }
        return player;
    }
}

// ============================================================================
// Singleton Export
// ============================================================================

// Export the singleton instance
export const wasmService = WasmService.getInstance();
